---
title: "kNN & Logit"
date: "2020-10-10"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ISLR)
library(class)
```


```{r}
attach(Auto)
mpg01 <- ifelse( mpg > median(mpg), yes = 1, no = 0)
Auto <- data.frame(Auto, mpg01)
```


```{r}
pairs(Auto) #scatterplot matrix

#boxplots
par(mfrow=c(2, 4))  
for (i in 2:9) {
  boxplot(Auto[, i] ~ Auto$mpg01, main = names(Auto)[i], xlab = "mpg01", 
          ylab = names(Auto)[i])
}
```

mpg01 is binary, and from the scatter plot matrix none seem obviously useful. Other features that seem like they could be useful are cylinders, displacement, horsepower, weight, and mpg.


```{r}
set.seed(123)
train_index <- sample(1:nrow(Auto), 0.7 * nrow(Auto))
train_set <- Auto[train_index, ]
test_set <- Auto[-train_index, ]
```



```{r}
logistic_model <- glm(mpg01 ~ cylinders + displacement + horsepower + weight + year, data = train_set, family = "binomial")

predictions <- predict(logistic_model, newdata = test_set, type = "response")
predicted_classes <- ifelse(predictions > 0.5, 1, 0) #convert prob to binary pred
confusion_matrix <- table(predicted_classes, test_set$mpg01) 

#accuracy
accuracy <- sum(diag(confusion_matrix)) / sum(confusion_matrix)
test_error <- 1 - accuracy

confusion_matrix
test_error
```


```{r}
predictors <- train_set[, c("cylinders", "displacement", "horsepower", "weight", "year")]
outcome <- train_set$mpg01

k_values <- c(1, 3, 5, 7, 9) #try k-values
test_errors <- numeric(length(k_values)) #vector to store Te errors

# kNN for each value of k
for (i in seq_along(k_values)) {
  predictions <- knn(train = predictors, test = test_set[, c("cylinders", "displacement", "horsepower", "weight", "year")], cl = outcome, k = k_values[i])

  #confusion matrix
  confusion_matrix <- table(predictions, test_set$mpg01)
  #accuracy
  accuracy <- sum(diag(confusion_matrix)) / sum(confusion_matrix)
  #test error
  test_error <- 1 - accuracy
  
    test_errors[i] <- test_error
}
data.frame(K = k_values, Test_Error = test_errors)
```

\(K=7\) has the lowest test error, so it seems to perform better when making predictions.













