---
title: "Simple Naive Bayes & CART"
date: "2021-10-10"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(e1071)
library(ISLR)
library(rpart)
wine <- read.csv("C:/Users/wine.csv", header=TRUE)
```

## NB

```{r}
train_data <- wine[sample(nrow(wine), 0.7 * nrow(wine)), ] #70-30 split
test_data <- wine[setdiff(1:nrow(wine), rownames(train_data)),]
```

```{r}
nb_model <- naiveBayes(Class ~ ., data = train_data)
nb_pred <- predict(nb_model, newdata = test_data)

accuracy_nb <- sum(nb_pred == test_data$Class) / nrow(test_data)
conf_matrix <- table(nb_pred, test_data$Class)
conf_matrix
cat("Naïve Bayes Accuracy:", accuracy_nb, "\n")
```


## CART

```{r}
set.seed(123)
train_data <- wine[sample(nrow(wine), 0.7 * nrow(wine)),] #70-30 split
test_data <- wine[setdiff(1:nrow(wine), rownames(train_data)),]
```

```{r}
cart_model <- rpart(Class ~ ., data = train_data)
cart_pred <- predict(cart_model, newdata = test_data)

accuracy_pred <- sum(cart_pred == test_data$Class) / nrow(test_data)
conf_matrix_cart <- table(cart_pred, test_data$Class)
cat("CART Accuracy:", accuracy_pred, "\n")
```

The Naive Bayes classifier model performed better than the CART, having a higher accuracy than CART.

